name: Deploy to staging server

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install SSH key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_STAGING }}
          username: ${{ secrets.USERNAME_STAGING }}
          key: ${{ secrets.SSH_KEY_STAGING }}
          script: |
            bash /home/ubuntu/deploy2.sh
